import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("TG TOP production bot links", () => {
  it("uses @TGTOP_robot for both channel and group admin onboarding", () => {
    const source = readFileSync(new URL("./Home.tsx", import.meta.url), "utf8");

    expect(source).toContain("https://t.me/TGTOP_robot?");
    expect(source).toContain("startchannel=admin");
    expect(source).toContain("startgroup=admin");
    expect(source).toContain('setAdminGuideKind(kind)');
    expect(source).toContain('tx("Подтвердите права администратора", "Confirm administrator rights")');
    expect(source).toContain('tx("В окне Telegram включите «Сделать администратором»."');
    expect(source).not.toContain("GiftsLabBot");
  });

  it("uses the shared GroupCard component for ranked and general catalog placements", () => {
    const source = readFileSync(new URL("./Home.tsx", import.meta.url), "utf8");

    expect(source).toContain('type GroupCardVariant = "lead" | "secondary" | "compact" | "list"');
    expect(source).toMatch(/<GroupCard\s+group=\{leadSlot\.group\}\s+variant="lead"/);
    expect(source).toContain('variant="secondary"');
    expect(source).toContain('variant="compact"');
    expect(source).toContain('h-[286px]');
    expect(source).toContain('sm:h-[42vh]');
    expect(source).toContain('h-[116px]');
    expect(source).toContain('h-[84px]');
    expect(source).toContain('max-w-full truncate');
    expect(source).toContain('max-w-[112px]');
    expect(source).toContain('min-w-0 flex-1 truncate text-lg');
    expect(source).toMatch(/<GroupCard\s+key=\{group\.id\}\s+group=\{group\}\s+variant="list"/);
    expect(source).toContain('В TG TOP пока нет площадок');
    expect(source).toContain('https://t.me/i/userpic/320/${group.username}.jpg');
    expect(source).toContain('className="absolute inset-0 grid place-items-center"');
    expect(source).toContain('className="absolute inset-0 h-full w-full object-cover"');
    expect(source).toContain('https://t.me/${group.username}');
    expect(source).toContain('onClick={event => event.stopPropagation()}');
    expect(source).toContain('className="no-underline hover:text-white"');
    expect(source).toContain('https://t.me/${group.username}');
    expect(source).not.toContain('underline-offset-2');
    expect(source).not.toContain('ПРОВЕРЕНА TG TOP');
    expect(source).toContain('tx("Перебить ставку", "Outbid placement")');
    expect(source).toContain('const formatTon = (value: number | string | null | undefined)');
    expect(source).toContain('tx(`Свободная позиция · от ${formatTon(0.1)} TON`');
    expect(source).not.toContain('0.100 TON');
    expect(source).toContain('tx("Снять с листинга", "Remove from listing")');
    expect(source).toContain('sticky top-2 z-10 flex items-center justify-between');
    expect(source).not.toContain('tx("Динамика аудитории", "Audience dynamics")');
    expect(source).not.toContain('{ value: "rent", title: tx("Аренда", "Rent")');
    expect(source).not.toContain('tx("Условия аренды", "Rental terms")');
    expect(source).toContain('["Каналы", ui.channels]');
    expect(source).toContain('["Чаты", ui.chats]');
    expect(source).toContain('["NFT", "NFT"]');
    expect(source).toContain('onClick={() => selectGlobalDirection(value)}');
    expect(source).toContain('globalDirection === "NFT"');
    expect(source).toContain('<NftCard');
    expect(source).toContain('value="onchain"');
    expect(source).toContain('value="offchain"');
    expect(source).toContain('prepareNftTransfer');
    expect(source).toContain('completeOffchainNftTransfer');
    expect(source).toContain('group.title.slice(0, 1).toUpperCase()');
    expect(source).not.toContain('accept="video/mp4"');
    expect(source).not.toContain('uploadSelectedAnimatedAvatar');
    expect(source).toContain('aria-live="polite"');
    expect(source).toContain('{n(globalCount, language)} {globalDirection === "NFT" ? "NFT" : ui.groups}');
    expect(source).toContain('Connect wallet');
    expect(source).toContain('useTonConnectUI');
    expect(source).toContain('tonConnectUi.openModal()');
    expect(source).toContain('language === "en" ? "Connected" : "Подключён"');
    expect(source).toContain('balanceTon} TON');
    expect(source).toContain('createStarsRankingPayment');
    expect(source).toContain('Оплатить Telegram Stars');
    expect(source).toContain('Record a TON bid without payment');
    expect(source).toContain('Добавить свою группу в список');
    expect(source).toContain('Добавить свою группу');
    expect(source).toContain('function OwnerEntry');
    expect(source).toContain('getPublicOwnerProfile.useQuery');
    expect(source).toContain('Разместил');
    expect(source).toContain('Профиль владельца');
    expect(source).toContain('getOwnerLeaderboard.useQuery');
    expect(source).toContain('Лидерборд владельцев');
    expect(source).toContain('По суммарной аудитории активных площадок в TG TOP.');
    expect(source).toContain('getAccountActivity.useQuery');
    expect(source).toContain('WebApp?.openInvoice');
    expect(source).toContain('Оплата подтверждена Telegram. Позиция обновляется…');
    expect(source).toContain('function NftShowcase');
    expect(source).toContain('NFT-витрина площадки');
    expect(source).toContain('NFT-витрина владельца');
    expect(source).toContain('Моя NFT-витрина');
    expect(source).toContain('setNftShowcase.mutate');
    expect(source).toContain('get("listing")');
    expect(source).toContain('setPage("details")');
    expect(source).toContain('tgtop_bot_observed');
    // expect(source).toContain('История до подключения бота не моделируется.');
    expect(source).toContain('История активности');
    expect(source).toContain('Реальные бонусы, ставки, Stars, сделки и передачи NFT.');
    expect(source).toContain('const verifiedTasks');
    expect(source).toContain('item.title === "manual_bonus" ? tx("Бонус TG TOP", "TG TOP bonus")');
    expect(source).toContain('const rankingMotionKey = `${globalDirection}:${category}:${subcategory}:${country}:${slotsQuery.dataUpdatedAt ?? 0}:${board.map');
    expect(source).toContain('className="ranking-slot-enter"');
    expect(source).toContain('Прогресс подтверждается только действиями, зафиксированными в TG TOP. Награды не начисляются автоматически.');
    expect(source).toContain('connect-community');
    expect(source).not.toContain('Connect Wallet появится после настройки TON Wallet.');
    expect(source).toContain('<WalletConnectControl language={language} balanceTon={formatTon(Number(mainTon))} />');
    expect(source).not.toContain('{ value: "system"');
    expect(source).toContain('setFiltersOpen(true)');
    expect(source).toContain('side="bottom"');
    expect(source).toContain('max-h-[62dvh] rounded-t-[22px]');
    expect(source).toContain('Настроить выдачу');
    expect(source).toContain('max-h-[34dvh] rounded-t-[20px]');
    expect(source).toContain('min-w-10 border-0 px-2 text-[10px]');
    expect(source).toContain('tx("Весь мир", "Worldwide")');
    expect(source).toContain('const COUNTRY_OPTIONS = ["Global", "UA", "PL", "DE", "GB", "US", "RU"] as const');
    expect(source).toContain('PL: { ru: "Польша", en: "Poland" }');
    expect(source).toContain('DE: { ru: "Германия", en: "Germany" }');
    expect(source).toContain('GB: { ru: "Великобритания", en: "United Kingdom" }');
    expect(source).toContain('getCountryLabel(country, language)');
    expect(source).not.toContain('"EU"');
    expect(source).toContain('const currentTopTitle = [');
    expect(source).toContain('tx("Все сообщества", "All communities")');
    expect(source).toContain('getSubcategoryLabel(subcategory, language)');
    expect(source).toContain('<h1 className="min-w-0 flex-1 truncate text-lg font-semibold tracking-tight text-white">{currentTopTitle}</h1>');
    expect(source).toContain('tx("Каталог групп", "Community catalog")');
    expect(source).toContain('tx("По этому фильтру площадок пока нет.", "No communities match this filter yet.")');
    expect(source).toContain('tx("Участники", "Members")');
    expect(source).toContain('tx("Приглашения", "Invites")');
    expect(source).toContain('tx("зафиксировано ботом", "recorded by the bot")');
    expect(source).toContain('sticky top-2 z-10 flex items-center justify-between');
    expect(source).toContain('tx("Загружаем статистику…", "Loading statistics…")');
    expect(source).toContain('"This placement will be available after the ranking board is created."');
    expect(source).toContain('const getProtectedDealGuidance = (status: string, isBuyer: boolean, buyerConfirmed = false) =>');
    expect(source).toContain('Transfer the Telegram owner rights before the 21-day deadline.');
    expect(source).toContain('confirmProtectedGroupTransfer');
    expect(source).toContain('Confirm receipt');
    expect(source).toContain('Settlement remains locked until payment verification.');
    expect(source).toContain('{getProtectedDealGuidance(deal.status, isBuyer, Boolean(deal.buyerConfirmedAt))}');
    expect(source).toContain('const [subcategory, setSubcategory] = useState("Все")');
    expect(source).toContain('getSlots.useQuery({');
    expect(source).toContain('subcategory,');
    expect(source).toContain('getGroups.useQuery({ category, country, subcategory })');
    expect(source).toContain('CATEGORY_SUBCATEGORIES');
    expect(source).toContain('setCountry(item)');
    expect(source).toContain('CATEGORY_SUBCATEGORIES[category].map(item =>');
    expect(source).toContain('setSubcategory("Все");');
    expect(source).toContain('setCountry("Все");');
  });
});
