import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("TG TOP production bot links", () => {
  it("uses @TGTOP_robot for both channel and group admin onboarding", () => {
    const source = readFileSync(new URL("./Home.tsx", import.meta.url), "utf8");

    expect(source).toContain("https://t.me/TGTOP_robot?");
    expect(source).toContain('startchannel&admin=${channelAdminRights}');
    expect(source).toContain('startgroup=tgtop_admin&admin=${groupAdminRights}');
    expect(source).toContain('delete_messages+invite_users+pin_messages+manage_chat');
    expect(source).toContain('setAdminGuideKind(kind)');
    expect(source).toContain('tx("Подтвердите права администратора", "Confirm administrator rights")');
    expect(source).toContain('Telegram should show Add as administrator, not Add as member.');
    expect(source).not.toContain("GiftsLabBot");
  });

  it("uses the shared GroupCard component for ranked and general catalog placements", () => {
    const source = readFileSync(new URL("./Home.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../index.css", import.meta.url), "utf8");

    expect(source).toContain('type GroupCardVariant = "lead" | "secondary" | "compact" | "list"');
    expect(source).toMatch(/<GroupCard\s+group=\{leadSlot\.group\}\s+variant="lead"/);
    expect(source).toContain('variant="secondary"');
    expect(source).toContain('variant="compact"');
    expect(source).toContain('h-[300px] border-[#3f8cff]/35 bg-[#141c27] p-5');
    expect(source).toContain('sm:h-[46vh]');
    expect(source).toContain('h-[128px] border-white/10 bg-[#111720] p-3');
    expect(source).toContain('h-[78px] border-white/8 bg-[#111720] p-2');
    expect(source).toContain('max-w-full truncate');
    expect(source).toContain('max-w-[132px]');
    expect(source).toContain('lead ? "text-xl" : compact ? "text-[11px]" : "text-sm"');
    expect(source).toMatch(/<GroupCard\s+key=\{group\.id\}\s+group=\{group\}\s+variant="list"/);
    expect(source).toContain('В TG TOP пока нет площадок');
    expect(source).toContain('https://t.me/i/userpic/320/${group.username}.jpg');
    expect(source).toContain('className="absolute inset-0 grid place-items-center"');
    expect(source).toContain('className="absolute inset-0 h-full w-full object-cover"');
    expect(source).toContain('https://t.me/${group.username}');
    expect(source).toContain('openTelegramCommunityLink(groupUrl)');
    expect(source).toContain('className="no-underline hover:text-white"');
    expect(source).toContain('https://t.me/${group.username}');
    expect(source).not.toContain('underline-offset-2');
    expect(source).not.toContain('ПРОВЕРЕНА TG TOP');
    expect(source).toContain('tx("Цена лота", "Lot price")');
    expect(source).toContain('const formatTon = (value: number | string | null | undefined)');
    expect(source).toContain('tx(`Свободная позиция · от ${amount} GRAM`');
    expect(source).not.toContain('0.100 TON');
    expect(source).not.toContain('{language === "en" ? "Catalog" : "Каталог"}');
    expect(source).toContain('tx("Снять с листинга", "Remove from listing")');
    expect(source).toContain('sticky top-2 z-10 flex items-center justify-between');
    expect(source).not.toContain('tx("Динамика аудитории", "Audience dynamics")');
    expect(source).not.toContain('{ value: "rent", title: tx("Аренда", "Rent")');
    expect(source).not.toContain('tx("Условия аренды", "Rental terms")');
    expect(source).toContain('["Каналы", ui.channels]');
    expect(source).toContain('["Чаты", ui.chats]');
    expect(source).toContain('["NFT", "NFT"]');
    expect(source).toContain('onClick={() => selectGlobalDirection(value)}');
    expect(source).toContain('globalDirection === "NFT"');
    expect(source).toContain('<NftCard');
    expect(source).toContain('value="onchain"');
    expect(source).toContain('value="offchain"');
    expect(source).toContain('prepareNftTransfer');
    expect(source).toContain('completeOffchainNftTransfer');
    expect(source).toContain('group.title.slice(0, 1).toUpperCase()');
    expect(source).not.toContain('accept="video/mp4"');
    expect(source).not.toContain('uploadSelectedAnimatedAvatar');
    expect(source).toContain('aria-live="polite"');
    expect(source).toContain('{n(globalCount, language)}</span>');
    expect(source).toContain('Connect wallet');
    expect(source).toContain('useTonConnectUI');
    expect(source).toContain('tonConnectUi.openModal()');
    expect(source).toContain('language === "en" ? "Connected" : "Подключён"');
    expect(source).toContain('balanceTon} TON');
    expect(source).toContain('createStarsRankingPayment');
    expect(source).toContain('Оплатить место');
    expect(source).toContain('шаг 0.1 GRAM');
    expect(source).toContain('getMinimumRankingBidGram');
    expect(source).toContain('<Slider value={[bidAmount]}');
    expect(source).not.toContain('Record a TON bid without payment');
    expect(source).toContain('Добавить свою группу в список');
    expect(source).toContain('Добавить свою группу');
    expect(source).not.toContain('function OwnerEntry');
    expect(source).toContain('getPublicOwnerProfile.useQuery');
    expect(source).toContain('const detailEntryUrl = detail?.group.monthlyEntryInviteLink ??');
    expect(source).toContain('tx("Перейти в группу", "Open community")');
    expect(source).toContain('tx("Перейти в приватную группу", "Open private community")');
    expect(source).toContain('ownsDetail && detail.group.status !== "listed"');
    expect(source).toContain('tx("Разместить в каталоге", "List in catalog")');
    expect(source).toContain('onClick={() => openListing([detail.group.id])}');
    expect(source).toContain('const detailMinimumBid = selectedSlot');
    expect(source).toContain('tx("Цена лота", "Lot price")');
    expect(source).toContain('formatPositionDuration(selectedSlot.updatedAt, positionClock)');
    expect(source).toContain('const hours = Math.floor(seconds / 3_600);');
    expect(source).not.toContain('const days = Math.floor(seconds / 86_400);');
    expect(source).toContain('!detailOwner ? (');
    expect(source).toContain('tx("Аноним", "Anonymous")');
    expect(source).toContain('const joinRewardUnits = rewardCampaignEnabled ? parseGramInput(rewardPerSubscription) : 0');
    expect(source).toContain('rewardPerInvite: isChatRewardCampaign ? 0 : joinRewardUnits');
    expect(source).toContain('Одна ставка применяется и к подписке, и к вступлению по персональной ссылке.');
    expect(source).toContain('rewardAmount?: number');
    expect(source).toContain('`Получите +${formatGram(group.rewardAmount!)} GRAM`');
    expect(source).toContain('className="absolute right-0 top-0 z-10 border-b border-l border-amber-100/25');
    expect(source).toContain('const getCommunityAccessLabel = (group: Pick<Group, "username">, language: Language)');
    expect(source).toContain('group.username ? `@${group.username}` : language === "en" ? "Private" : "Приватный"');
    expect(source).toContain('detailOwner &&');
    expect(source).toContain('tx("Мои группы", "My groups")');
    expect(source).not.toContain('tx("Личная папка", "Personal cabinet")');
    expect(source).toContain('tx("Разместил", "Listed by")');
    expect(source).not.toContain('onOwnerClick');
    expect(source).toContain('Профиль владельца');
    expect(source).toContain('getOwnerLeaderboard.useQuery');
    expect(source).toContain('Лидерборд владельцев');
    expect(source).toContain('По суммарной аудитории активных площадок в TG TOP.');
    expect(source).toContain('getAccountActivity.useQuery');
    expect(source).toContain('WebApp?.openInvoice');
    expect(source).toContain('Оплата подтверждена Telegram. Позиция обновляется…');
    expect(source).toContain('function NftShowcase');
    expect(source).toContain('NFT-витрина площадки');
    expect(source).toContain('NFT-витрина владельца');
    expect(source).toContain('Моя NFT-витрина');
    expect(source).toContain('setNftShowcase.mutate');
    expect(source).toContain('get("listing")');
    expect(source).toContain('setPage("details")');
    expect(source).toContain('tgtop_bot_observed');
    // expect(source).toContain('История до подключения бота не моделируется.');
    expect(source).toContain('История активности');
    expect(source).toContain('Реальные бонусы, ставки, Stars, сделки и передачи NFT.');
    expect(source).toContain('const verifiedTasks');
    expect(source).toContain('item.title === "manual_bonus" ? tx("Бонус TG TOP", "TG TOP bonus")');
    expect(source).toContain('const rankingMotionKey = `${globalDirection}:${category}:${subcategory}:${country}:${city}`');
    expect(source).toContain('import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"');
    expect(source).not.toContain('const canApplyAnonymousListing = selectedListingGroups.length > 0');
    expect(source).not.toContain('anonymousListing: selectedListingGroups.length ? anonymousListing : undefined');
    expect(source).not.toContain('Переключить анонимное размещение');
    expect(source).not.toContain('const [anonymousListing, setAnonymousListing] = useState(true)');
    expect(source).toContain('!detailOwner ? (');
    expect(source).toContain('tx("Аноним", "Anonymous")');
    expect(source).toContain('Подписаться и получить +${formatGram(subscriptionReward)} GRAM');
    expect(source).toContain('<Select value={listingCountry}');
    expect(source).toContain('<Select value={listingSubcategory}');
    expect(source).toContain('fixed inset-x-3 bottom-[calc(6.75rem+env(safe-area-inset-bottom))] z-50');
    expect(source).toContain('tx("Снять выделение", "Clear selection")');
    expect(source).toContain('tx("Отменить", "Cancel")');
    expect(source).toContain('tx("Снять с каталога", "Remove from catalog")');
    expect(source).toContain('setListingSubcategory(selectedGroupsShareCategory ? firstGroup?.subcategory ?? "General" : "")');
    expect(source).toContain('subcategory: listingCategory && listingSubcategory ? listingSubcategory : undefined');
    expect(source).toContain('h-[68px] border-white/8 bg-[#111720] px-3 py-2');
    expect(source).toContain('group relative flex h-[68px] w-full items-center justify-between gap-3 overflow-hidden rounded-xl');
    expect(source).toContain('flex h-14 w-full items-center justify-center gap-2 rounded-2xl border border-dashed');
    expect(source).toContain('targetSlot ? "min-h-[116px]" : "h-[64px]"');
    expect(source).toContain('absolute right-3 top-1/2 z-10 grid h-5 w-5 -translate-y-1/2');
    expect(source).toContain('relative h-6 w-11 shrink-0 rounded-full border transition-colors');
    expect(source).toContain('absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white shadow-sm transition-transform');
    expect(source).toContain('translate-x-6');
    expect(source).not.toContain('Подкатегории задаются отдельно для каналов и чатов.');
    expect(source).toContain('className="ranking-slot-enter ranking-slot-lead w-full"');
    expect(source).toContain('type MyGroupsViewMode = "list" | "grid"');
    expect(source).toContain('const [myGroupsViewMode, setMyGroupsViewMode] = useState<MyGroupsViewMode>("list")');
    expect(source).toContain('myGroupsViewMode === "grid"');
    expect(source).not.toContain('myGroupsViewMode === "top"');
    expect(source).toContain('rounded-full border px-2.5 text-[9px]');
    expect(source).not.toContain('CatalogViewMode');
    expect(styles).toContain('--ranking-slot-offset: 26px');
    expect(styles).toContain('.ranking-slot-enter { animation: ranking-slot-enter 360ms');
    expect(source).toContain('isEnglish ? "For sale" : "На продаже"');
    expect(source).toContain('tx(`Купить за ${formatTon(detail.group.salePriceTon)} TON`');
    expect(source).toContain('isEnglish ? "In catalog" : "В каталоге"');
    expect(source).not.toContain('isEnglish ? "Unlisted" : "Не в листинге"');
    expect(source).toContain('ownsDetail && detail.group.category === "Чаты"');
    expect(source).toContain('role="switch"');
    expect(source).toContain('translate-x-6');
    expect(source).toContain('trpc.tgTop.saveMyGroupsLayout.useMutation');
    expect(source).toContain('<DndContext\n                  sensors={myGroupsSensors}');
    expect(source).toContain('SortableMyGroupTile');
    expect(source).toContain('tx("Закреплено", "Pinned")');
    expect(source).toContain('activationConstraint: { delay: 320, tolerance: 10 }');
    expect(source).toContain('myGroupsStatusFilter');
    expect(source).toContain('const [myGroupsSelectionMode, setMyGroupsSelectionMode] = useState(false)');
    expect(source).toContain('tx("Выбрать", "Select")');
    expect(source).toContain('beginMyGroupsSelectionHold(group.id)');
    expect(source).toContain('const [myGroupsSearchQuery, setMyGroupsSearchQuery] = useState("")');
    expect(source).toContain('const isMyGroupsSearchActive = normalizedMyGroupsSearch.length > 0');
    expect(source).toContain('myGroupsViewMode === "grid" && !targetSlot && !isMyGroupsSearchActive');
    expect(source).toContain('visibleMyGroupsMembers');
    expect(source).toContain('setMyGroupsAddOpen(true)');
    expect(source).toContain('grid grid-cols-3 gap-2');
    expect(source).toContain('Тяните за ручку, чтобы менять порядок');
    expect(source).toContain('DragOverlay dropAnimation');
    expect(source).toContain('setMyGroupsDragActiveId(Number(active.id))');
    expect(source).toContain('tx("Перемещение", "Moving")');
    expect(source).toContain('setActivatorNodeRef');
    expect(source).toContain('GripVertical');
    expect(source).toContain('[-webkit-touch-callout:none]');
    expect(source).toContain('selectGlobalDirection(value)');
    expect(source).toContain('tx("Выставить на продажу", "Offer for sale")');
    expect(source).toContain('isListingForSale && (');
    expect(source).toContain('Прогресс подтверждается только действиями, зафиксированными в TG TOP. Награды не начисляются автоматически.');
    expect(source).toContain('connect-community');
    expect(source).not.toContain('Connect Wallet появится после настройки TON Wallet.');
    expect(source).toContain('<WalletConnectControl language={language} balanceTon={formatTon(Number(mainTon))} variant="profile" />');
    expect(source).not.toContain('{ value: "system"');
    expect(source).toContain('setFiltersOpen(true)');
    expect(source).toContain('side="bottom"');
    expect(source).toContain('max-h-[82dvh] rounded-t-[22px]');
    expect(source).toContain('Настроить выдачу');
    expect(source).toContain('const CITY_OPTIONS');
    expect(source).toContain('setCity("Все")');
    expect(source).not.toContain('tx("Анонимное размещение", "Anonymous listing")');
    expect(source).toContain('Показать контакт владельца');
    expect(source).toContain('setPublicProfile.mutate({ publicProfile: !account?.user?.publicProfile })');
    expect(source).toContain('Вы появитесь в списке, только если сделаете профиль публичным.');
    expect(source).toContain('tx("Вознаграждения", "Rewards")');
    expect(source).toContain('rewardCampaignEnabled');
    expect(source).toContain('rewardBudget: budgetUnits');
    expect(source).toContain('rewardPerSubscription: isChatRewardCampaign ? 0 : joinRewardUnits');
    expect(source).toContain('rewardPerInvite: isChatRewardCampaign ? 0 : joinRewardUnits');
    expect(source).toContain('rewardPerManualAdd: isChatRewardCampaign ? joinRewardUnits : 0');
    expect(source).toContain('className="group relative flex h-[68px] w-full items-center justify-between gap-3 overflow-hidden rounded-xl');
    expect(source).toContain('tx("Цена в GRAM", "Price in GRAM")');
    expect(source).not.toContain('Telegram поддерживает платный вход Stars только для каналов.');
    expect(source).toContain('formatPositionDuration(selectedSlot.updatedAt, positionClock)');
    expect(source).toContain('tx("Цена лота", "Lot price")');
    expect(source).toContain('openTelegramCommunityLink(`https://t.me/${detailOwner.telegramUsername}`)');
    expect(source).toContain('const rankSlotId = Number(params.get("rankSlot"));');
    expect(source).toContain('setRankSlotLinkId(rankSlotId)');
    expect(source).toContain('const detailEntryUrl = detail?.group.monthlyEntryInviteLink ??');
    expect(source).toContain('detailHasPaidEntry');
    expect(source).toContain('tx(`Войти за ${detail.group.monthlyEntryStars} Stars`');
    expect(source).toContain('tx("Сделать вход платным", "Make entry paid")');
    expect(source).toContain('max-h-[34dvh] rounded-t-[20px]');
    expect(source).toContain('min-w-10 border-0 px-2 text-[10px]');
    expect(source).toContain('tx("Весь мир", "Worldwide")');
    expect(source).toContain('<Input value={topSearchQuery} onChange={event => setTopSearchQuery(event.target.value)}');
    expect(source).toContain('globalDirection === "NFT" ? tx("Поиск NFT", "Search NFT")');
    expect(source).toContain('`${nft.username} ${nft.ownerUsername}`.toLowerCase().includes(query)');
    expect(source).toContain('!topSearchQuery.trim() && <div key={rankingMotionKey}');
    expect(source).toContain('bg-emerald-500/30 text-emerald-50');
    expect(source).toContain('clip-path:polygon(12px_0,100%_0,100%_100%,0_100%,0_12px)');
    expect(source).toContain('const rankingPriceLabel = bidAmount > 0');
    expect(source).toContain('`${formatTon(bidAmount / 1000)} GRAM`');
    expect(source).toContain('bidAmount={leadSlot.bidAmount}');
    expect(source).toContain('grid-cols-4 grid-rows-3 gap-[2px]');
    expect(source).toContain('col-start-2 row-start-1');
    expect(source).toContain('const COUNTRY_OPTIONS = ["Global", "UA", "PL", "DE", "GB", "US", "RU", "FR", "ES", "IT", "NL", "CZ", "RO", "TR", "CA", "AU", "AE", "KZ"] as const');
    expect(source).toContain('PL: { ru: "Польша", en: "Poland" }');
    expect(source).toContain('DE: { ru: "Германия", en: "Germany" }');
    expect(source).toContain('GB: { ru: "Великобритания", en: "United Kingdom" }');
    expect(source).toContain('getCountryLabel(country, language)');
    expect(source).not.toContain('"EU"');
    expect(source).toContain('const currentTopTitle = [');
    expect(source).toContain('tx("Все сообщества", "All communities")');
    expect(source).toContain('getSubcategoryLabel(subcategory, language)');
    expect(source).toContain('const currentTopCountry = globalDirection !== "NFT" && country !== "Все"');
    expect(source).toContain('const currentTopCity = globalDirection !== "NFT" && city !== "Все"');
    expect(source).toContain('max-h-[264px] space-y-1 overflow-y-auto pr-1');
    expect(source).toContain('tx("Каталог групп", "Community catalog")');
    expect(source).toContain('tx("По этому фильтру площадок пока нет.", "No communities match this filter yet.")');
    expect(source).toContain('tx("Участники", "Members")');
    expect(source).toContain('tx("Приглашения", "Invites")');
    expect(source).toContain('tx("зафиксировано ботом", "recorded by the bot")');
    expect(source).toContain('sticky top-2 z-10 flex items-center justify-between');
    expect(source).toContain('tx("Загружаем статистику…", "Loading statistics…")');
    expect(source).toContain('"This placement will be available after the ranking board is created."');
    expect(source).toContain('const getProtectedDealGuidance = (status: string, isBuyer: boolean, buyerConfirmed = false) =>');
    expect(source).toContain('Transfer the Telegram owner rights before the 21-day deadline.');
    expect(source).toContain('confirmProtectedGroupTransfer');
    expect(source).toContain('Confirm receipt');
    expect(source).toContain('Settlement remains locked until payment verification.');
    expect(source).toContain('{getProtectedDealGuidance(deal.status, isBuyer, Boolean(deal.buyerConfirmedAt))}');
    expect(source).toContain('const [subcategory, setSubcategory] = useState("Все")');
    expect(source).toContain('getSlots.useQuery({');
    expect(source).toContain('subcategory,');
    expect(source).toContain('getGroups.useQuery({ category, country, subcategory, city })');
    expect(source).toContain('CATEGORY_SUBCATEGORIES');
    expect(source).toContain('setCountry(item)');
    expect(source).toContain('CATEGORY_SUBCATEGORIES[category].map(item =>');
    expect(source).toContain('setSubcategory("Все");');
    expect(source).toContain('setCountry("Все");');
  });
});
