export interface MockCatalogTaxonomy {
  countries: Array<{ id: number; code: string; label: string; sortOrder: number }>;
  cities: Array<{ id: number; countryCode: string; code: string; label: string; sortOrder: number }>;
  topics: Array<{ id: number; category: "Каналы" | "Чаты" | "Боты"; code: string; label: string; sortOrder: number }>;
}

export const mockTaxonomy: MockCatalogTaxonomy = {
  countries: [
    { id: 1, code: "Global", label: "Весь мир", sortOrder: 1 },
    { id: 2, code: "RU", label: "Россия", sortOrder: 2 },
    { id: 3, code: "KZ", label: "Казахстан", sortOrder: 3 },
    { id: 4, code: "BY", label: "Беларусь", sortOrder: 4 },
    { id: 5, code: "UZ", label: "Узбекистан", sortOrder: 5 },
  ],
  cities: [
    { id: 1, countryCode: "RU", code: "MSK", label: "Москва", sortOrder: 1 },
    { id: 2, countryCode: "RU", code: "SPB", label: "Санкт-Петербург", sortOrder: 2 },
    { id: 3, countryCode: "KZ", code: "ALA", label: "Алматы", sortOrder: 3 },
    { id: 4, countryCode: "BY", code: "MSQ", label: "Минск", sortOrder: 4 },
    { id: 5, countryCode: "UZ", code: "TAS", label: "Ташкент", sortOrder: 5 },
  ],
  topics: [
    { id: 1, category: "Каналы", code: "tech", label: "Технологии", sortOrder: 1 },
    { id: 2, category: "Каналы", code: "crypto", label: "Криптовалюта и TON", sortOrder: 2 },
    { id: 3, category: "Каналы", code: "news", label: "Новости и СМИ", sortOrder: 3 },
    { id: 4, category: "Каналы", code: "business", label: "Бизнес и стартапы", sortOrder: 4 },
    { id: 5, category: "Каналы", code: "entertainment", label: "Юмор и развлечения", sortOrder: 5 },
    { id: 6, category: "Каналы", code: "education", label: "Образование и наука", sortOrder: 6 },
    { id: 7, category: "Чаты", code: "tech", label: "IT & Разработка", sortOrder: 1 },
    { id: 8, category: "Чаты", code: "crypto", label: "Web3 & TON", sortOrder: 2 },
    { id: 9, category: "Чаты", code: "business", label: "Предприниматели", sortOrder: 3 },
    { id: 10, category: "Чаты", code: "general", label: "Общение", sortOrder: 4 },
    { id: 11, category: "Боты", code: "tools", label: "Инструменты", sortOrder: 1 },
    { id: 12, category: "Боты", code: "ai", label: "ИИ и Ассистенты", sortOrder: 2 },
    { id: 13, category: "Боты", code: "games", label: "Игры и Web3", sortOrder: 3 },
  ],
};

export const mockGroups = [
  {
    id: 1,
    chatId: "-1001122334455",
    title: "Telegram News",
    username: "telegram",
    inviteLink: "https://t.me/telegram",
    description: "Официальный новостной канал Telegram с ключевыми анонсами, релизами версий и обновлениями платформы.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: "https://telegram.org/img/t_logo.png",
    animatedAvatarUpdatedAt: null,
    membersCount: 6280000,
    ownerOpenId: "owner_telegram_official",
    category: "Каналы" as const,
    subcategory: "news",
    country: "Global",
    city: null,
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-01"),
    messagesCount: 1420,
    joinedCount: 154000,
    leavesCount: 2200,
    invitedCount: 0,
    lastPostViews: 1250000,
    lastPostAt: new Date(),
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-01"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "midnight",
    anonymousListing: false,
    showOwnerContact: false,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: true,
    ownerSortOrder: 1,
    createdAt: new Date("2025-01-01"),
    rewardAmount: 0,
    owner: {
      openId: "owner_telegram_official",
      name: "Telegram Team",
      telegramUsername: "telegram",
    },
  },
  {
    id: 2,
    chatId: "-1001122334456",
    title: "Durov's Channel",
    username: "durov",
    inviteLink: "https://t.me/durov",
    description: "Личный канал основателя Telegram Павла Дурова. Мысли о свободе, децентрализации, технологиях и развитии экосистемы.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: "https://telegram.org/img/t_logo.png",
    animatedAvatarUpdatedAt: null,
    membersCount: 2750000,
    ownerOpenId: "owner_durov",
    category: "Каналы" as const,
    subcategory: "tech",
    country: "Global",
    city: null,
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-02"),
    messagesCount: 380,
    joinedCount: 94000,
    leavesCount: 800,
    invitedCount: 0,
    lastPostViews: 2100000,
    lastPostAt: new Date(),
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-02"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "ocean",
    anonymousListing: false,
    showOwnerContact: false,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: true,
    ownerSortOrder: 2,
    createdAt: new Date("2025-01-02"),
    rewardAmount: 0,
    owner: {
      openId: "owner_durov",
      name: "Pavel Durov",
      telegramUsername: "durov",
    },
  },
  {
    id: 3,
    chatId: "-1001122334457",
    title: "TON Community",
    username: "tonblockchain",
    inviteLink: "https://t.me/tonblockchain",
    description: "Официальное русскоязычное сообщество блокчейна The Open Network. Новости экосистемы, гранты, хакатоны и обновления.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: "https://ton.org/download/ton_symbol.png",
    animatedAvatarUpdatedAt: null,
    membersCount: 1940000,
    ownerOpenId: "owner_ton",
    category: "Каналы" as const,
    subcategory: "crypto",
    country: "Global",
    city: null,
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-03"),
    messagesCount: 2200,
    joinedCount: 65000,
    leavesCount: 1200,
    invitedCount: 0,
    lastPostViews: 480000,
    lastPostAt: new Date(),
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-03"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "sunset",
    anonymousListing: false,
    showOwnerContact: false,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: true,
    ownerSortOrder: 3,
    createdAt: new Date("2025-01-03"),
    rewardAmount: 0,
    owner: {
      openId: "owner_ton",
      name: "TON Foundation",
      telegramUsername: "tonblockchain",
    },
  },
  {
    id: 4,
    chatId: "-1001122334458",
    title: "Код Дурова",
    username: "d_code",
    inviteLink: "https://t.me/d_code",
    description: "Медиа об IT, технологиях, Telegram, гаджетах и цифровом будущем с эксклюзивными инсайдами.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: null,
    animatedAvatarUpdatedAt: null,
    membersCount: 432000,
    ownerOpenId: "owner_dcode",
    category: "Каналы" as const,
    subcategory: "tech",
    country: "RU",
    city: "MSK",
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-04"),
    messagesCount: 5400,
    joinedCount: 18000,
    leavesCount: 400,
    invitedCount: 0,
    lastPostViews: 190000,
    lastPostAt: new Date(),
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-04"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "emerald",
    anonymousListing: false,
    showOwnerContact: false,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: false,
    ownerSortOrder: 4,
    createdAt: new Date("2025-01-04"),
    rewardAmount: 0,
    owner: {
      openId: "owner_dcode",
      name: "Редакция Код Дурова",
      telegramUsername: "d_code",
    },
  },
  {
    id: 5,
    chatId: "-1001122334459",
    title: "Хабр IT",
    username: "habr_com",
    inviteLink: "https://t.me/habr_com",
    description: "Канал русскоязычного сообщества разработчиков Habr. Подборки лучших статей, новости софта и карьера в IT.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: null,
    animatedAvatarUpdatedAt: null,
    membersCount: 298000,
    ownerOpenId: "owner_habr",
    category: "Каналы" as const,
    subcategory: "tech",
    country: "RU",
    city: "SPB",
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-05"),
    messagesCount: 3800,
    joinedCount: 11000,
    leavesCount: 250,
    invitedCount: 0,
    lastPostViews: 85000,
    lastPostAt: new Date(),
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-05"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "sapphire",
    anonymousListing: false,
    showOwnerContact: false,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: false,
    ownerSortOrder: 5,
    createdAt: new Date("2025-01-05"),
    rewardAmount: 0,
    owner: {
      openId: "owner_habr",
      name: "Habr",
      telegramUsername: "habr_com",
    },
  },
  {
    id: 6,
    chatId: "-1001122334460",
    title: "Эксплойт",
    username: "exploitex",
    inviteLink: "https://t.me/exploitex",
    description: "Медиа о цифровой безопасности, технологических утечках, уязвимостях и полезном софте.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: null,
    animatedAvatarUpdatedAt: null,
    membersCount: 524000,
    ownerOpenId: "owner_exploit",
    category: "Каналы" as const,
    subcategory: "tech",
    country: "Global",
    city: null,
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-06"),
    messagesCount: 4600,
    joinedCount: 22000,
    leavesCount: 500,
    invitedCount: 0,
    lastPostViews: 240000,
    lastPostAt: new Date(),
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-06"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "midnight",
    anonymousListing: false,
    showOwnerContact: false,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: false,
    ownerSortOrder: 6,
    createdAt: new Date("2025-01-06"),
    rewardAmount: 0,
    owner: {
      openId: "owner_exploit",
      name: "Exploit Media",
      telegramUsername: "exploitex",
    },
  },
  {
    id: 7,
    chatId: "-1001122334461",
    title: "TON Developers RU",
    username: "tondev_ru",
    inviteLink: "https://t.me/tondev_ru",
    description: "Крупнейший чат разработчиков на TON: FunC, Tact, Blueprint, Telegram Mini Apps и смарт-контракты.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: "https://ton.org/download/ton_symbol.png",
    animatedAvatarUpdatedAt: null,
    membersCount: 48500,
    ownerOpenId: "owner_tondev",
    category: "Чаты" as const,
    subcategory: "tech",
    country: "Global",
    city: null,
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-07"),
    messagesCount: 84000,
    joinedCount: 3100,
    leavesCount: 80,
    invitedCount: 0,
    lastPostViews: 0,
    lastPostAt: null,
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-07"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "ocean",
    anonymousListing: false,
    showOwnerContact: true,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: false,
    ownerSortOrder: 7,
    createdAt: new Date("2025-01-07"),
    rewardAmount: 0,
    owner: {
      openId: "owner_tondev",
      name: "TON Core Community",
      telegramUsername: "tondev_ru",
    },
  },
  {
    id: 8,
    chatId: "-1001122334462",
    title: "Startup & Venture Chat",
    username: "rus_startups",
    inviteLink: "https://t.me/rus_startups",
    description: "Чат фаундеров, венчурных инвесторов, бизнес-ангелов и продакт-менеджеров. Нетворкинг и поиск партнеров.",
    avatarFileId: null,
    animatedAvatarKey: null,
    animatedAvatarUrl: null,
    animatedAvatarUpdatedAt: null,
    membersCount: 36200,
    ownerOpenId: "owner_venture",
    category: "Чаты" as const,
    subcategory: "business",
    country: "RU",
    city: "MSK",
    status: "listed" as const,
    moderationStatus: "approved" as const,
    moderationReason: null,
    moderationReviewedBy: "admin",
    moderationReviewedAt: new Date("2025-01-08"),
    messagesCount: 62000,
    joinedCount: 1900,
    leavesCount: 40,
    invitedCount: 0,
    lastPostViews: 0,
    lastPostAt: null,
    lastStatsAt: new Date(),
    listedAt: new Date("2025-01-08"),
    salePriceTon: null,
    listingType: "catalog" as const,
    cardBackgroundPreset: "sunset",
    anonymousListing: false,
    showOwnerContact: true,
    managerTelegramUserId: null,
    managerUsername: null,
    managerName: null,
    managerAvatarUrl: null,
    managerPublic: true,
    listingAnnouncementEnabled: true,
    searchIndexable: true,
    monthlyEntryEnabled: false,
    monthlyEntryStars: null,
    monthlyEntryLinkName: null,
    monthlyEntryInviteLink: null,
    monthlyEntryUpdatedAt: null,
    rewardActive: false,
    rewardBudget: 0,
    rewardPerSubscription: 0,
    rewardPerInvite: 0,
    rewardPerManualAdd: 1,
    deleteServiceMessages: false,
    ownerPinned: false,
    ownerSortOrder: 8,
    createdAt: new Date("2025-01-08"),
    rewardAmount: 0,
    owner: {
      openId: "owner_venture",
      name: "Venture Club",
      telegramUsername: "rus_startups",
    },
  },
];

export const mockAuctionSlots = [
  {
    id: 1,
    slotNumber: 1,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "1 место в ТОП",
    subtitle: "Лидер общего рейтинга",
    currentBid: "150 TON",
    bidAmount: 150000,
    leaderUsername: "durov",
    leaderUserId: "10001",
    groupId: 2,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[1],
  },
  {
    id: 2,
    slotNumber: 2,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "2 место в ТОП",
    subtitle: "Официальные новости",
    currentBid: "120 TON",
    bidAmount: 120000,
    leaderUsername: "telegram",
    leaderUserId: "10002",
    groupId: 1,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[0],
  },
  {
    id: 3,
    slotNumber: 3,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "3 место в ТОП",
    subtitle: "Экосистема TON",
    currentBid: "95 TON",
    bidAmount: 95000,
    leaderUsername: "tonblockchain",
    leaderUserId: "10003",
    groupId: 3,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[2],
  },
  {
    id: 4,
    slotNumber: 4,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "4 место в ТОП",
    subtitle: "Технологическое медиа",
    currentBid: "60 TON",
    bidAmount: 60000,
    leaderUsername: "d_code",
    leaderUserId: "10004",
    groupId: 4,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[3],
  },
  {
    id: 5,
    slotNumber: 5,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "5 место в ТОП",
    subtitle: "Информационная безопасность",
    currentBid: "45 TON",
    bidAmount: 45000,
    leaderUsername: "exploitex",
    leaderUserId: "10005",
    groupId: 6,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[5],
  },
  {
    id: 6,
    slotNumber: 6,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "6 место в ТОП",
    subtitle: "IT Сообщество",
    currentBid: "30 TON",
    bidAmount: 30000,
    leaderUsername: "habr_com",
    leaderUserId: "10006",
    groupId: 5,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[4],
  },
  {
    id: 7,
    slotNumber: 7,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "7 место в ТОП",
    subtitle: "Чат разработчиков",
    currentBid: "20 TON",
    bidAmount: 20000,
    leaderUsername: "tondev_ru",
    leaderUserId: "10007",
    groupId: 7,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[6],
  },
  {
    id: 8,
    slotNumber: 8,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "8 место в ТОП",
    subtitle: "Стартапы и инвестиции",
    currentBid: "15 TON",
    bidAmount: 15000,
    leaderUsername: "rus_startups",
    leaderUserId: "10008",
    groupId: 8,
    updatedAt: new Date(),
    isOccupied: true,
    group: mockGroups[7],
  },
  {
    id: 9,
    slotNumber: 9,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "Свободное место #9",
    subtitle: "Открыто для ставок",
    currentBid: "0.1 TON",
    bidAmount: 100,
    leaderUsername: "-",
    leaderUserId: null,
    groupId: null,
    updatedAt: new Date(),
    isOccupied: false,
    group: null,
  },
  {
    id: 10,
    slotNumber: 10,
    category: "Все" as const,
    subcategory: "Все",
    country: "Global",
    title: "Свободное место #10",
    subtitle: "Открыто для ставок",
    currentBid: "0.1 TON",
    bidAmount: 100,
    leaderUsername: "-",
    leaderUserId: null,
    groupId: null,
    updatedAt: new Date(),
    isOccupied: false,
    group: null,
  },
];

export const mockApprovedBots = [
  {
    id: 1,
    username: "Wallet",
    telegramLink: "https://t.me/wallet",
    category: "Инструменты",
    createdAt: new Date("2025-01-01"),
    moderationReviewedAt: new Date("2025-01-01"),
  },
  {
    id: 2,
    username: "BotFather",
    telegramLink: "https://t.me/botfather",
    category: "Инструменты",
    createdAt: new Date("2025-01-01"),
    moderationReviewedAt: new Date("2025-01-01"),
  },
  {
    id: 3,
    username: "Stickers",
    telegramLink: "https://t.me/stickers",
    category: "Инструменты",
    createdAt: new Date("2025-01-01"),
    moderationReviewedAt: new Date("2025-01-01"),
  },
  {
    id: 4,
    username: "donate",
    telegramLink: "https://t.me/donate",
    category: "Инструменты",
    createdAt: new Date("2025-01-01"),
    moderationReviewedAt: new Date("2025-01-01"),
  },
];
